// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Redhead.SitesCatalog.Infrastructure.Data;

#nullable disable

namespace Redhead.SitesCatalog.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260605031708_AddClientExportUsageLimits")]
    partial class AddClientExportUsageLimits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<int?>("DailyExportOperationsLimitOverride")
                        .HasColumnType("integer");

                    b.Property<int?>("DailyUniqueExportedDomainsLimitOverride")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("ExportLimitOverrideMode")
                        .HasColumnType("integer");

                    b.Property<int?>("ExportLimitRowsOverride")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("SuperAdminNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("WeeklyExportOperationsLimitOverride")
                        .HasColumnType("integer");

                    b.Property<int?>("WeeklyUniqueExportedDomainsLimitOverride")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AspNetUsers_DailyExportOperationsLimitOverride_PositiveOrNull", "\"DailyExportOperationsLimitOverride\" IS NULL OR \"DailyExportOperationsLimitOverride\" > 0");

                            t.HasCheckConstraint("CK_AspNetUsers_DailyUniqueExportedDomainsLimitOverride_PositiveOrNull", "\"DailyUniqueExportedDomainsLimitOverride\" IS NULL OR \"DailyUniqueExportedDomainsLimitOverride\" > 0");

                            t.HasCheckConstraint("CK_AspNetUsers_ExportLimitOverride_LimitedRequiresRows", "\"ExportLimitOverrideMode\" IS NULL OR \"ExportLimitOverrideMode\" <> 2 OR (\"ExportLimitRowsOverride\" IS NOT NULL AND \"ExportLimitRowsOverride\" > 0)");

                            t.HasCheckConstraint("CK_AspNetUsers_ExportLimitOverride_NonLimitedRequiresNullRows", "\"ExportLimitOverrideMode\" IS NULL OR \"ExportLimitOverrideMode\" = 2 OR \"ExportLimitRowsOverride\" IS NULL");

                            t.HasCheckConstraint("CK_AspNetUsers_ExportLimitOverride_NullModeRequiresNullRows", "\"ExportLimitOverrideMode\" IS NOT NULL OR \"ExportLimitRowsOverride\" IS NULL");

                            t.HasCheckConstraint("CK_AspNetUsers_ExportLimitOverride_ValidMode", "\"ExportLimitOverrideMode\" IS NULL OR \"ExportLimitOverrideMode\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_AspNetUsers_WeeklyExportOperationsLimitOverride_PositiveOrNull", "\"WeeklyExportOperationsLimitOverride\" IS NULL OR \"WeeklyExportOperationsLimitOverride\" > 0");

                            t.HasCheckConstraint("CK_AspNetUsers_WeeklyUniqueExportedDomainsLimitOverride_PositiveOrNull", "\"WeeklyUniqueExportedDomainsLimitOverride\" IS NULL OR \"WeeklyUniqueExportedDomainsLimitOverride\" > 0");
                        });
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.CanonicalLocation", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Key");

                    b.HasIndex("DisplayName");

                    b.HasIndex("SortOrder");

                    b.ToTable("CanonicalLocations", (string)null);
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.ExportAnalyticsSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExportLogId")
                        .HasColumnType("uuid");

                    b.Property<string>("FiltersSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SearchSnapshotJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("SnapshotVersion")
                        .HasColumnType("integer");

                    b.Property<string>("SortSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ExportLogId")
                        .IsUnique();

                    b.ToTable("ExportAnalyticsSnapshots", (string)null);
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.ExportLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlockedReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("DailyExportOperationsLimit")
                        .HasColumnType("integer");

                    b.Property<int?>("DailyUniqueExportedDomainsLimit")
                        .HasColumnType("integer");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ExportLimitRows")
                        .HasColumnType("integer");

                    b.Property<string>("ExportMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ExportedRowsCount")
                        .HasColumnType("integer");

                    b.Property<int>("RequestedRowsCount")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RowsReturned")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("WasTruncated")
                        .HasColumnType("boolean");

                    b.Property<int?>("WeeklyExportOperationsLimit")
                        .HasColumnType("integer");

                    b.Property<int?>("WeeklyUniqueExportedDomainsLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Destination");

                    b.HasIndex("ExportMode");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("UserId", "TimestampUtc", "BlockedReason");

                    b.ToTable("ExportLogs", (string)null);
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.ExportedDomainAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ExportLogId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExportedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("Domain");

                    b.HasIndex("ExportLogId");

                    b.HasIndex("ExportedAtUtc");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ExportedAtUtc");

                    b.HasIndex("UserId", "Domain", "ExportedAtUtc");

                    b.ToTable("ExportedDomainAccesses", (string)null);
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.GoogleDriveConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ConnectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExportFolderId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExportFolderName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GoogleEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GoogleSubjectId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GrantedScopes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RefreshTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("GoogleEmail");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"RevokedAtUtc\" IS NULL");

                    b.ToTable("GoogleDriveConnections", (string)null);
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.ImportLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Duplicates")
                        .HasColumnType("integer");

                    b.Property<int>("ErrorsCount")
                        .HasColumnType("integer");

                    b.Property<int>("Inserted")
                        .HasColumnType("integer");

                    b.Property<int>("Matched")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Unmatched")
                        .HasColumnType("integer");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("ImportLogs", (string)null);
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.LocationGroup", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Key");

                    b.HasIndex("Kind", "SortOrder");

                    b.ToTable("LocationGroups", (string)null);
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.LocationGroupItem", b =>
                {
                    b.Property<string>("GroupKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LocationKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("GroupKey", "LocationKey");

                    b.HasIndex("LocationKey");

                    b.ToTable("LocationGroupItems", (string)null);
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.RoleSettings", b =>
                {
                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("DailyExportOperationsLimit")
                        .HasColumnType("integer");

                    b.Property<int?>("DailyUniqueExportedDomainsLimit")
                        .HasColumnType("integer");

                    b.Property<int>("ExportLimitMode")
                        .HasColumnType("integer");

                    b.Property<int?>("ExportLimitRows")
                        .HasColumnType("integer");

                    b.Property<int?>("WeeklyExportOperationsLimit")
                        .HasColumnType("integer");

                    b.Property<int?>("WeeklyUniqueExportedDomainsLimit")
                        .HasColumnType("integer");

                    b.HasKey("RoleName");

                    b.ToTable("RoleSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_RoleSettings_DailyExportOperationsLimit_PositiveOrNull", "\"DailyExportOperationsLimit\" IS NULL OR \"DailyExportOperationsLimit\" > 0");

                            t.HasCheckConstraint("CK_RoleSettings_DailyUniqueExportedDomainsLimit_PositiveOrNull", "\"DailyUniqueExportedDomainsLimit\" IS NULL OR \"DailyUniqueExportedDomainsLimit\" > 0");

                            t.HasCheckConstraint("CK_RoleSettings_ExportLimitMode_ValidValue", "\"ExportLimitMode\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_RoleSettings_ExportLimitRows_LimitedRequiresRows", "\"ExportLimitMode\" <> 2 OR (\"ExportLimitRows\" IS NOT NULL AND \"ExportLimitRows\" > 0)");

                            t.HasCheckConstraint("CK_RoleSettings_ExportLimitRows_NonLimitedRequiresNullRows", "\"ExportLimitMode\" = 2 OR \"ExportLimitRows\" IS NULL");

                            t.HasCheckConstraint("CK_RoleSettings_WeeklyExportOperationsLimit_PositiveOrNull", "\"WeeklyExportOperationsLimit\" IS NULL OR \"WeeklyExportOperationsLimit\" > 0");

                            t.HasCheckConstraint("CK_RoleSettings_WeeklyUniqueExportedDomainsLimit_PositiveOrNull", "\"WeeklyUniqueExportedDomainsLimit\" IS NULL OR \"WeeklyUniqueExportedDomainsLimit\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            RoleName = "SuperAdmin",
                            ExportLimitMode = 3
                        },
                        new
                        {
                            RoleName = "Admin",
                            ExportLimitMode = 3
                        },
                        new
                        {
                            RoleName = "Internal",
                            ExportLimitMode = 2,
                            ExportLimitRows = 10000
                        },
                        new
                        {
                            RoleName = "Client",
                            DailyExportOperationsLimit = 20,
                            DailyUniqueExportedDomainsLimit = 1000,
                            ExportLimitMode = 2,
                            ExportLimitRows = 5000,
                            WeeklyExportOperationsLimit = 60,
                            WeeklyUniqueExportedDomainsLimit = 3000
                        });
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.Site", b =>
                {
                    b.Property<string>("Domain")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Categories")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<double>("DR")
                        .HasColumnType("double precision");

                    b.Property<string>("ImportedLocationRaw")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsQuarantined")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("LastPublishedDate")
                        .HasColumnType("date");

                    b.Property<bool>("LastPublishedDateIsMonthOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LocationKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Niche")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("NicheTokens")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<int?>("NumberDFLinks")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PriceCasino")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<short>("PriceCasinoStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<decimal?>("PriceCrypto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<short>("PriceCryptoStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<decimal?>("PriceDating")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<short>("PriceDatingStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<decimal?>("PriceLinkInsert")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("PriceLinkInsertCasino")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<short>("PriceLinkInsertCasinoStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<short>("PriceLinkInsertStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<decimal?>("PriceUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("QuarantineReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("QuarantineUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SponsoredTag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short?>("TermType")
                        .HasColumnType("smallint");

                    b.Property<short?>("TermUnit")
                        .HasColumnType("smallint");

                    b.Property<int?>("TermValue")
                        .HasColumnType("integer");

                    b.Property<long>("Traffic")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("Domain");

                    b.HasIndex("Categories")
                        .HasDatabaseName("IX_Sites_Categories_Trgm")
                        .HasFilter("\"Categories\" IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Categories"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Categories"), new[] { "gin_trgm_ops" });

                    b.HasIndex("DR");

                    b.HasIndex("IsQuarantined");

                    b.HasIndex("Location");

                    b.HasIndex("LocationKey");

                    b.HasIndex("NicheTokens");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NicheTokens"), "gin");

                    b.HasIndex("NumberDFLinks");

                    b.HasIndex("PriceUsd");

                    b.HasIndex("Traffic");

                    b.HasIndex("LastPublishedDate", "LastPublishedDateIsMonthOnly", "Domain");

                    b.HasIndex("TermType", "TermUnit", "TermValue");

                    b.ToTable("Sites", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sites_NumberDFLinks_PositiveOrNull", "\"NumberDFLinks\" IS NULL OR \"NumberDFLinks\" > 0");

                            t.HasCheckConstraint("CK_Sites_PriceCasino_StatusConsistency", "(\"PriceCasinoStatus\" = 1 AND \"PriceCasino\" IS NOT NULL AND \"PriceCasino\" > 0) OR (\"PriceCasinoStatus\" IN (0, 2, 3) AND \"PriceCasino\" IS NULL)");

                            t.HasCheckConstraint("CK_Sites_PriceCrypto_StatusConsistency", "(\"PriceCryptoStatus\" = 1 AND \"PriceCrypto\" IS NOT NULL AND \"PriceCrypto\" > 0) OR (\"PriceCryptoStatus\" IN (0, 2, 3) AND \"PriceCrypto\" IS NULL)");

                            t.HasCheckConstraint("CK_Sites_PriceDating_StatusConsistency", "(\"PriceDatingStatus\" = 1 AND \"PriceDating\" IS NOT NULL AND \"PriceDating\" > 0) OR (\"PriceDatingStatus\" IN (0, 2, 3) AND \"PriceDating\" IS NULL)");

                            t.HasCheckConstraint("CK_Sites_PriceLinkInsertCasino_StatusConsistency", "(\"PriceLinkInsertCasinoStatus\" = 1 AND \"PriceLinkInsertCasino\" IS NOT NULL AND \"PriceLinkInsertCasino\" > 0) OR (\"PriceLinkInsertCasinoStatus\" IN (0, 2, 3) AND \"PriceLinkInsertCasino\" IS NULL)");

                            t.HasCheckConstraint("CK_Sites_PriceLinkInsert_StatusConsistency", "(\"PriceLinkInsertStatus\" = 1 AND \"PriceLinkInsert\" IS NOT NULL AND \"PriceLinkInsert\" > 0) OR (\"PriceLinkInsertStatus\" IN (0, 2, 3) AND \"PriceLinkInsert\" IS NULL)");

                            t.HasCheckConstraint("CK_Sites_PriceUsd_PositiveOrNull", "\"PriceUsd\" IS NULL OR \"PriceUsd\" > 0");

                            t.HasCheckConstraint("CK_Sites_Term_Consistency", "(\"TermType\" IS NULL AND \"TermValue\" IS NULL AND \"TermUnit\" IS NULL) OR (\"TermType\" = 1 AND \"TermValue\" IS NULL AND \"TermUnit\" IS NULL) OR (\"TermType\" = 2 AND \"TermValue\" IS NOT NULL AND \"TermValue\" > 0 AND \"TermUnit\" = 1)");
                        });
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.SystemJobArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalFileId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("StorageProvider")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SystemJobRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExternalFileId");

                    b.HasIndex("SystemJobRunId");

                    b.ToTable("SystemJobArtifacts", null, t =>
                        {
                            t.HasCheckConstraint("CK_SystemJobArtifacts_FileSizeBytes_NonNegative", "\"FileSizeBytes\" >= 0");
                        });
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.SystemJobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("JobName", "PeriodKey")
                        .IsUnique()
                        .HasDatabaseName("UX_SystemJobRuns_JobName_PeriodKey_Succeeded")
                        .HasFilter("\"Status\" = 2");

                    b.ToTable("SystemJobRuns", null, t =>
                        {
                            t.HasCheckConstraint("CK_SystemJobRuns_Status_ValidValue", "\"Status\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.UserSavedFilterSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TableKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TableKey", "NormalizedName")
                        .IsUnique();

                    b.ToTable("UserSavedFilterSets", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserSavedFilterSets_SchemaVersion", "\"SchemaVersion\" = 1");

                            t.HasCheckConstraint("CK_UserSavedFilterSets_SettingsJsonLength", "length(\"SettingsJson\"::text) <= 2097152");

                            t.HasCheckConstraint("CK_UserSavedFilterSets_TableKey", "\"TableKey\" = 'sites'");
                        });
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.UserTableCustomView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TableKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TableKey", "NormalizedName")
                        .IsUnique();

                    b.ToTable("UserTableCustomViews", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserTableCustomViews_SchemaVersion", "\"SchemaVersion\" = 1");

                            t.HasCheckConstraint("CK_UserTableCustomViews_SettingsJsonLength", "length(\"SettingsJson\"::text) <= 16384");

                            t.HasCheckConstraint("CK_UserTableCustomViews_TableKey", "\"TableKey\" = 'sites'");
                        });
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.UserTablePreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveViewKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActiveViewType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TableKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TableKey")
                        .IsUnique();

                    b.ToTable("UserTablePreferences", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserTablePreferences_ActiveViewType", "\"ActiveViewType\" IN ('system', 'custom')");

                            t.HasCheckConstraint("CK_UserTablePreferences_TableKey", "\"TableKey\" = 'sites'");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Redhead.SitesCatalog.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Redhead.SitesCatalog.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Redhead.SitesCatalog.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Redhead.SitesCatalog.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.ExportAnalyticsSnapshot", b =>
                {
                    b.HasOne("Redhead.SitesCatalog.Domain.Entities.ExportLog", "ExportLog")
                        .WithOne("AnalyticsSnapshot")
                        .HasForeignKey("Redhead.SitesCatalog.Domain.Entities.ExportAnalyticsSnapshot", "ExportLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExportLog");
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.ExportedDomainAccess", b =>
                {
                    b.HasOne("Redhead.SitesCatalog.Domain.Entities.ExportLog", "ExportLog")
                        .WithMany("ExportedDomainAccesses")
                        .HasForeignKey("ExportLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExportLog");
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.GoogleDriveConnection", b =>
                {
                    b.HasOne("Redhead.SitesCatalog.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.LocationGroupItem", b =>
                {
                    b.HasOne("Redhead.SitesCatalog.Domain.Entities.LocationGroup", "Group")
                        .WithMany("Items")
                        .HasForeignKey("GroupKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Redhead.SitesCatalog.Domain.Entities.CanonicalLocation", "Location")
                        .WithMany("GroupItems")
                        .HasForeignKey("LocationKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.Site", b =>
                {
                    b.HasOne("Redhead.SitesCatalog.Domain.Entities.CanonicalLocation", "CanonicalLocation")
                        .WithMany("Sites")
                        .HasForeignKey("LocationKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CanonicalLocation");
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.SystemJobArtifact", b =>
                {
                    b.HasOne("Redhead.SitesCatalog.Domain.Entities.SystemJobRun", "SystemJobRun")
                        .WithMany("Artifacts")
                        .HasForeignKey("SystemJobRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemJobRun");
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.UserSavedFilterSet", b =>
                {
                    b.HasOne("Redhead.SitesCatalog.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.UserTableCustomView", b =>
                {
                    b.HasOne("Redhead.SitesCatalog.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.UserTablePreference", b =>
                {
                    b.HasOne("Redhead.SitesCatalog.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.CanonicalLocation", b =>
                {
                    b.Navigation("GroupItems");

                    b.Navigation("Sites");
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.ExportLog", b =>
                {
                    b.Navigation("AnalyticsSnapshot");

                    b.Navigation("ExportedDomainAccesses");
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.LocationGroup", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.SystemJobRun", b =>
                {
                    b.Navigation("Artifacts");
                });
#pragma warning restore 612, 618
        }
    }
}
