// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Redhead.SitesCatalog.Infrastructure.Data;

#nullable disable

namespace Redhead.SitesCatalog.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.ExportLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FilterSummaryJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RowsReturned")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("ExportLogs", (string)null);
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.ImportLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Duplicates")
                        .HasColumnType("integer");

                    b.Property<int>("ErrorsCount")
                        .HasColumnType("integer");

                    b.Property<int>("Inserted")
                        .HasColumnType("integer");

                    b.Property<int>("Matched")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Unmatched")
                        .HasColumnType("integer");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("ImportLogs", (string)null);
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.RoleSettings", b =>
                {
                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ExportLimitRows")
                        .HasColumnType("integer");

                    b.HasKey("RoleName");

                    b.ToTable("RoleSettings", (string)null);

                    b.HasData(
                        new
                        {
                            RoleName = "SuperAdmin",
                            ExportLimitRows = 1000000
                        },
                        new
                        {
                            RoleName = "Admin",
                            ExportLimitRows = 1000000
                        },
                        new
                        {
                            RoleName = "Internal",
                            ExportLimitRows = 10000
                        },
                        new
                        {
                            RoleName = "Client",
                            ExportLimitRows = 5000
                        });
                });

            modelBuilder.Entity("Redhead.SitesCatalog.Domain.Entities.Site", b =>
                {
                    b.Property<string>("Domain")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Categories")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DR")
                        .HasColumnType("integer");

                    b.Property<bool>("IsQuarantined")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Niche")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("PriceCasino")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("PriceCrypto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("PriceLinkInsert")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PriceUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("QuarantineReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("QuarantineUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Traffic")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Domain");

                    b.HasIndex("DR");

                    b.HasIndex("IsQuarantined");

                    b.HasIndex("Location");

                    b.HasIndex("PriceUsd");

                    b.HasIndex("Traffic");

                    b.ToTable("Sites", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
